version: "3.7"
services:
  api:
    container_name: terraswap-service
    volumes:
      - ./:/app:ro
    build:
      context: .
      target: build
    ports:
      - ${SERVER_PORT:-8000}:${SERVER_PORT:-8000}
    command: sh -c "GO111MODULE=off go get github.com/cortesi/modd/cmd/modd && make watch"
    networks:
      - local-api

  db:
    container_name: terraswap-db
    image: postgres:13
    volumes:
      - ./database/data:/var/lib/postgres
    ports:
      - ${TERRASWAP_DB_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${TERRASWAP_DB_PASSWORD:-password}
    networks:
      - local-api
  

networks:
  local-api:
    driver: bridge