api:
  name: terraswap-service
  host: 0.0.0.0
  port: 8000
  swagger: false
  mod: release # test, debug, release
  env:

sentry:
  # "https://putYourSentry@sentry.io/Id"
  dsn:

log:
  # panic, fatal, error, warn, info, debug, trace
  level: info
  formatJson: true
  # prod, dev
  env:

terraswap:
  chainId: pisco-1
  version: # Optional v1 or v2 for columbus
  grpcHost: pisco-grpc.terra.dev:443
  insecureConnection: false
  cw20AllowlistUrl: https://assets.terra.money/cw20/tokens.json
  ibcAllowlistUrl: https://assets.terra.money/ibc/tokens.json
  filterUnverified: false

rdb:
  host:
  port:
  database:
  username:
  password:

cache:
  host:
  db:
  tlsRequired:
  ca:
  authRequired:
  password:
