name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        args: --timeout=5m --enable=unparam --enable=misspell --enable=prealloc --tests=false --disable=errcheck

    - name: Tests
      shell: bash
      run: |
        make test

    - name: Build all
      run: make main && make build-api
